language:
  c

branches:
  only:
  - master

script:
  - mkdir build && cd build && cmake ..
  - make
  - ./scc ../tests/factory.c
  - ./scc ../tests/fibonacci.c
  - ./scc ../tests/full_syntax_errors.c
  - ./scc ../tests/full_semantic_errors.c

compiler:
  - clang
  - gcc
