language:
  c

compiler:
  - clang
  - gcc

install:
  - sudo apt-get install spim

script:
  - mkdir build && cd build && cmake ..
  - make
  - ./scc ../tests/factory.c -o ./factory.asm
  - if [[ "$((echo "10" | spim -file ./factory.asm) | grep "3628800")" != "3628800" ]]; then exit $?; fi
  - ./scc ../tests/fibonacci.c -o ./fibonacci.asm
  - if [[ "$((echo "10" | spim -file ./fibonacci.asm) | grep "55")" != "55" ]]; then exit $?; fi
  - ./scc ../tests/full_syntax_errors.c
  - ./scc ../tests/full_semantic_errors.c

branches:
  only:
  - master
